// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SistemaVeterinario.Infrastructure.Data;

#nullable disable

namespace SistemaVeterinario.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaVeterinario.API.Models.Pet", b =>
                {
                    b.Property<decimal>("IdPet")
                        .HasPrecision(10)
                        .HasColumnType("DECIMAL(10,0)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("CorPet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("COR_PET");

                    b.Property<DateTime>("DataCadastroPet")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO_PET");

                    b.Property<DateTime>("DataNascimentoPet")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_NASCIMENTO_PET");

                    b.Property<string>("EspeciePet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ESPECIE_PET");

                    b.Property<decimal>("IdTutor")
                        .HasPrecision(10)
                        .HasColumnType("DECIMAL(10,0)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<string>("NomePet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_PET");

                    b.Property<decimal>("PesoPet")
                        .HasPrecision(5, 2)
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("PESO_PET");

                    b.Property<string>("RacaPet")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("RACA_PET");

                    b.Property<string>("SexoPet")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("SEXO_PET");

                    b.HasKey("IdPet");

                    b.HasIndex("IdTutor");

                    b.ToTable("TB_PET", (string)null);
                });

            modelBuilder.Entity("SistemaVeterinario.API.Models.Tutor", b =>
                {
                    b.Property<decimal>("IdTutor")
                        .HasPrecision(10)
                        .HasColumnType("DECIMAL(10,0)")
                        .HasColumnName("ID_TUTOR");

                    b.Property<string>("BairroTutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("BAIRRO_TUTOR");

                    b.Property<string>("CepTutor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("CEP_TUTOR");

                    b.Property<string>("CidadeTutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CIDADE_TUTOR");

                    b.Property<string>("ComplementoTutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("COMPLEMENTO_TUTOR");

                    b.Property<string>("CpfTutor")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CPF_TUTOR");

                    b.Property<DateTime>("DataCadastroTutor")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO_TUTOR");

                    b.Property<string>("EmailTutor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL_TUTOR");

                    b.Property<string>("EstadoTutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ESTADO_TUTOR");

                    b.Property<string>("NomeTutor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME_TUTOR");

                    b.Property<string>("NumeroTutor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NUMERO_TUTOR");

                    b.Property<string>("RuaTutor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("RUA_TUTOR");

                    b.Property<string>("TelefoneTutor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE_TUTOR");

                    b.HasKey("IdTutor");

                    b.ToTable("TB_TUTOR", (string)null);
                });

            modelBuilder.Entity("SistemaVeterinario.API.Models.Veterinario", b =>
                {
                    b.Property<decimal>("IdVeterinario")
                        .HasPrecision(10)
                        .HasColumnType("DECIMAL(10,0)")
                        .HasColumnName("ID_VETERINARIO");

                    b.Property<string>("CrmVeterinario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CRM_VETERINARIO");

                    b.Property<DateTime>("DataCadastroVeterinario")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO_VETERINARIO");

                    b.Property<string>("EmailVeterinario")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("EMAIL_VETERINARIO");

                    b.Property<string>("EspecialidadeVeterinario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ESPECIALIDADE_VETERINARIO");

                    b.Property<string>("NomeVeterinario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME_VETERINARIO");

                    b.Property<string>("StatusVeterinario")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS_VETERINARIO");

                    b.Property<string>("TelefoneVeterinario")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TELEFONE_VETERINARIO");

                    b.HasKey("IdVeterinario");

                    b.HasIndex("CrmVeterinario")
                        .IsUnique();

                    b.HasIndex("EmailVeterinario")
                        .IsUnique()
                        .HasFilter("\"EMAIL_VETERINARIO\" IS NOT NULL");

                    b.ToTable("TB_VETERINARIO", (string)null);
                });

            modelBuilder.Entity("SistemaVeterinario.API.Models.Pet", b =>
                {
                    b.HasOne("SistemaVeterinario.API.Models.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tutor");
                });
#pragma warning restore 612, 618
        }
    }
}
